export const getVideos = async () => {
  return [
    {
      id: 1,
      name: 'Video 1',
      campaign: 'Campaign 1',
      duration: '00:30',
      creativeURL: 'https://www.youtube.com/watch?v=6JYIGclVQdw',
      vastURL: 'https://www.youtube.com/watch?v=6JYIGclVQdw',
      reproductions: 1234237,
      dataTransfer: 294343,
      emissions: 1234237,
    },
    {
      id: 2,
      name: 'Video 2',
      campaign: 'Campaign 2',
      duration: '00:30',
      creativeURL: 'https://www.youtube.com/watch?v=6JYIGclVQdw',
      vastURL: 'https://www.youtube.com/watch?v=6JYIGclVQdw',
      reproductions: 1234237,
      dataTransfer: 294343,
      emissions: 1234237,
    },
    {
      id: 3,
      name: 'Video 3',
      campaign: 'Campaign 3',
      duration: '00:30',
      creativeURL: 'https://www.youtube.com/watch?v=6JYIGclVQdw',
      vastURL: 'https://www.youtube.com/watch?v=6JYIGclVQdw',
      reproductions: 1234237,
      dataTransfer: 294343,
      emissions: 1234237,
    },
    {
      id: 4,
      name: 'Video 4',
      campaign: 'Campaign 4',
      duration: '00:30',
      creativeURL: 'https://www.youtube.com/watch?v=6JYIGclVQdw',
      vastURL: 'https://www.youtube.com/watch?v=6JYIGclVQdw',
      reproductions: 1234237,
      dataTransfer: 294343,
      emissions: 1234237,
    },
    {
      id: 5,
      name: 'Video 5',
      campaign: 'Campaign 5',
      duration: '00:30',
      creativeURL: 'https://www.youtube.com/watch?v=6JYIGclVQdw',
      vastURL: 'https://www.youtube.com/watch?v=6JYIGclVQdw',
      reproductions: 1234237,
      dataTransfer: 294343,
      emissions: 1234237,
    },
  ];
};
