name: S3 Sync Action

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Connect to aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-session-name: awssyncsession
          role-to-assume: ${{secrets.AWS_IAM_ROLE}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: sync bucket
        run: aws s3 sync ./dist/ s3://${{ secrets.AWS_BUCKET_NAME }} --delete
